[tool.poetry]
name = "pyb4model"
version = "0.1.0"
description = "A python package to preprocess data and conduct machine learning!"
authors = ["Andrea <andrea.lee.011@gmail.com>", "Jake", "Sakariya", "Xinwen"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
